AWSTemplateFormatVersion: 2010-09-09
Description: 'ACM Certificate for CloudFront - must be deployed in us-east-1'
Parameters:
  Name:
    Description: >-
      Is ultimately the leading moniker in the hostname (e.g. $name.example.com)
    Type: String
    Default: cdn
  ResourceSuffix:
    Description: >-
      A LOWER CASE suffix for the certificate domain - this
      allows multiple certificates to be created for different environments.
    Type: String
    MinLength: '0'
    MaxLength: '255'
    AllowedPattern: '[_a-z0-9-]*'
    ConstraintDescription: contain only lower case alphanumeric characters.
  DnsZone:
    Description: >-
      Amazon Route53 ZONE Name. This is the zone where a DNS record will be
      created for the web app. The name should NOT end with a period.
    Type: String
    Default: example.com
  HostedZoneId:
    Description: >-
      Amazon Route53 Hosted Zone ID. This is the zone where a DNS record will be
      created for the verification of the certificate requested. It should match the
      one from the DnsZone paramter.
    Type: String
  CertificateMode:
    Description: >-
      Certificate mode: 'single' for {Name}.{DnsZone} (default),
      'wildcard' for *.{DnsZone}
    Type: String
    Default: single
    AllowedValues:
      - single
      - wildcard
  IncludeRootDomain:
    Description: >-
      Include root domain ({DnsZone}) as Subject Alternative Name.
      Useful to cover the bare domain alongside a subdomain or wildcard.
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
Conditions:
  HasResourceSuffix: !Not
    - !Equals
      - !Ref ResourceSuffix
      - ''
  IsSingleMode: !Equals
    - !Ref CertificateMode
    - single
  IsWildcardMode: !Equals
    - !Ref CertificateMode
    - wildcard
  IncludeRoot: !Equals
    - !Ref IncludeRootDomain
    - 'true'
Resources:
  AcmCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !If
        - IsSingleMode
        - !Join
          - ''
          - - !Ref Name
            - !If
              - HasResourceSuffix
              - !Join
                - ''
                - - '-'
                  - !Ref ResourceSuffix
              - !Ref 'AWS::NoValue'
            - .
            - !Ref DnsZone
        - !Join
          - ''
          - - '*.'
            - !Ref DnsZone
      SubjectAlternativeNames: !If
        - IncludeRoot
        - - !Ref DnsZone
        - !Ref 'AWS::NoValue'
      DomainValidationOptions:
        - DomainName: !If
            - IsSingleMode
            - !Join
              - ''
              - - !Ref Name
                - !If
                  - HasResourceSuffix
                  - !Join
                    - ''
                    - - '-'
                      - !Ref ResourceSuffix
                  - !Ref 'AWS::NoValue'
                - .
                - !Ref DnsZone
            - !Join
              - ''
              - - '*.'
                - !Ref DnsZone
          HostedZoneId: !Ref HostedZoneId
        - !If
          - IncludeRoot
          - DomainName: !Ref DnsZone
            HostedZoneId: !Ref HostedZoneId
          - !Ref 'AWS::NoValue'
      ValidationMethod: DNS
Outputs:
  CertificateArn:
    Description: ARN of the ACM Certificate (must be created in us-east-1 for CloudFront)
    Value: !Ref AcmCertificate
    Export:
      Name: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - CertificateArn
