AWSTemplateFormatVersion: 2010-09-09
Description: 'Content distribution template (S3 bucket, CloudFront distribution, etc.)'
Parameters:
  Name:
    Description: >-
      Is ultimately the leading moniker in the bucket and hostname (e.g. $name.example.com)
    Type: String
    Default: cdn
  Stage:
    Description: >-
      Describes the stage for this environment and is used in bucket name. (e.g
      $name-$stage-$region-$account[-$suffix]).
    Type: String
    Default: main
  ResourceSuffix:
    Description: >-
      A LOWER CASE suffix for any resources created by this region script - this
      allows multiple sets of resources to be in one region.
    Type: String
    MinLength: '0'
    MaxLength: '255'
    AllowedPattern: '[_a-z0-9-]*'
    ConstraintDescription: contain only lower case alphanumeric characters.
  DnsZone:
    Description: >-
      Amazon Route53 ZONE Name. This is the zone where a DNS record will be
      created for the web app. The name should NOT end with a period.
    Type: String
    Default: example.com
  AcmCertificateArn:
    Description: >-
      ARN of the ACM Certificate to use for CloudFront. This certificate MUST be
      created in us-east-1 region (use the acm_certificate.yaml stack in us-east-1).
    Type: String
    Default: 'arn:aws:acm:us-east-1:123456789012:certificate/00000000-0000-0000-0000-000000000000'
Conditions:
  HasResourceSuffix: !Not
    - !Equals
      - !Ref ResourceSuffix
      - ''
Resources:
  ContentBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Join
        - '-'
        - - !Ref Name
          - !Ref Stage
          - !Ref 'AWS::Region'
          - !Ref 'AWS::AccountId'
          - !If
            - HasResourceSuffix
            - !Ref ResourceSuffix
            - !Ref 'AWS::NoValue'
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Identity for CDN
  ContentBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref ContentBucket
      PolicyDocument:
        Version: 2012-10-17
        Id: BucketAccessPolicy
        Statement:
          - Sid: AllowCloudFrontAccess
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt
                - CloudFrontOriginAccessIdentity
                - S3CanonicalUserId
            Action: 's3:GetObject'
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref ContentBucket
                  - /*
  ContentCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Comment: Default caching policy
        Name: !Join
          - '-'
          - - 'cdn-master'
            - !Ref 'AWS::StackName'
        DefaultTTL: 86400
        MinTTL: 300
        MaxTTL: 86400
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none
  ContentDistribution:
    Type: 'AWS::CloudFront::Distribution'
    DeletionPolicy: Retain
    Properties:
      DistributionConfig:
        Aliases:
          - !Join
            - ''
            - - !Ref Name
              - !If
                - HasResourceSuffix
                - !Join
                  - ''
                  - - '-'
                    - !Ref ResourceSuffix
                - !Ref 'AWS::NoValue'
              - .
              - !Ref DnsZone
        Origins:
          - DomainName: !GetAtt
              - ContentBucket
              - RegionalDomainName
            Id: !Join
              - '-'
              - - s3
                - !Ref ContentBucket
            S3OriginConfig:
              OriginAccessIdentity: !Join
                - '/'
                - - 'origin-access-identity'
                  - 'cloudfront'
                  - !Ref CloudFrontOriginAccessIdentity
        Enabled: 'true'
        Comment: S3 bucket content
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachePolicyId: !Ref ContentCachePolicy
          Compress: true
          TargetOriginId: !Join
            - '-'
            - - s3
              - !Ref ContentBucket
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100
        HttpVersion: http2
        ViewerCertificate:
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2019
          AcmCertificateArn: !Ref AcmCertificateArn
  CdnRecordset:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneName: !Join
        - ''
        - - !Ref DnsZone
          - .
      Name: !Join
        - ''
        - - !Ref Name
          - !If
            - HasResourceSuffix
            - !Join
              - ''
              - - '-'
                - !Ref ResourceSuffix
            - !Ref 'AWS::NoValue'
          - .
          - !Ref DnsZone
          - .
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt
          - ContentDistribution
          - DomainName
  CdnRecordsetIPv6:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneName: !Join
        - ''
        - - !Ref DnsZone
          - .
      Name: !Join
        - ''
        - - !Ref Name
          - !If
            - HasResourceSuffix
            - !Join
              - ''
              - - '-'
                - !Ref ResourceSuffix
            - !Ref 'AWS::NoValue'
          - .
          - !Ref DnsZone
          - .
      Type: AAAA
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt
          - ContentDistribution
          - DomainName
Outputs:
  ContentBucket:
    Description: Content S3 bucket name
    Value: !Ref ContentBucket
    Export:
      Name: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - ContentBucket
  CdnUrl:
    Description: CDN URL
    Value: !Join
      - ''
      - - 'https://'
        - !Ref CdnRecordset
        - /
    Export:
      Name: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - CdnUrl
